-- Run against Supabase with an administrative database connection.
-- All fixtures and mutations are rolled back, including Auth users.
begin;
do $$
declare owner uuid:=gen_random_uuid(); other_owner uuid:=gen_random_uuid(); shop uuid:=gen_random_uuid(); other_shop uuid:=gen_random_uuid(); template uuid; member uuid; new_member uuid; aid bigint; result jsonb; original jsonb; test_payload jsonb; version timestamptz; slug text:='test-plans-'||shop::text; d date:=current_date+1; rejected boolean;
begin
 insert into auth.users(id,email) values(owner,owner::text||'@example.invalid'),(other_owner,other_owner::text||'@example.invalid');
 test_payload:=jsonb_build_object('shopName','Temporary test shop','shopPhone','','shopAddress','','services',jsonb_build_array(jsonb_build_object('id',1,'name','Corte','duration',30,'price',40,'active',true),jsonb_build_object('id',2,'name','Barba','duration',30,'price',25,'active',true)),'barbers',jsonb_build_array(jsonb_build_object('id',1,'name','Profissional','active',true)),'appointments','[]'::jsonb,'clients','[]'::jsonb,'bookingStart','08:00','bookingEnd','18:00','bookingInterval',60,'serviceDayRules','{}'::jsonb);
 insert into public.barbershops(id,owner_id,name,phone,address,slug,payload) values(shop,owner,'Temporary test shop','','',slug,test_payload),(other_shop,other_owner,'Other temporary shop','','','other-'||slug,test_payload);
 perform set_config('request.jwt.claim.sub',owner::text,true);
 perform set_config('request.jwt.claims',jsonb_build_object('sub',owner,'role','authenticated')::text,true);
 template:=public.save_customer_plan(shop,null,'Corte e barba',100,30,'[{"serviceId":1,"quantity":1},{"serviceId":2,"quantity":2}]',true);
 rejected:=false; begin perform public.save_customer_plan(other_shop,null,'Forbidden',10,30,'[{"serviceId":1,"quantity":1}]',true); exception when others then rejected:=true; end;
 if not rejected then raise exception 'Tenant isolation failed'; end if;
 rejected:=false; begin perform public.activate_customer_plan(shop,template,'Test client','11111111111','27999990000',current_date,'123456'); exception when others then rejected:=true; end;
 if not rejected then raise exception 'Invalid CPF accepted'; end if;
 member:=public.activate_customer_plan(shop,template,'Test client','52998224725','27999990000',current_date,'123456');
 result:=public.lookup_customer_plan(slug,'52998224725','999999');
 if not result ? 'error' then raise exception 'Wrong PIN accepted'; end if;
 result:=public.lookup_customer_plan('other-'||slug,'52998224725','123456');
 if not result ? 'error' then raise exception 'Cross-shop lookup accepted'; end if;
 result:=public.lookup_customer_plan('non-existent','52998224725','123456');
 if not result ? 'error' then raise exception 'Unknown shop error missing'; end if;
 original:=public.lookup_customer_plan(slug,'52998224725','123456');
 if original ? 'cpf' or original ? 'client_name' or original ? 'phone' or original->>'planName'<>'Corte e barba' then raise exception 'Public plan leaked identity or wrong plan'; end if;
 select updated_at,payload into version,test_payload from public.barbershops where id=shop;
 result:=public.create_plan_booking(slug,'52998224725','123456','Ignored name','Ignored phone',1,'Profissional',d,'08:00'); aid:=(result->>'appointmentId')::bigint;
 if aid is null or not exists(select 1 from public.customer_plan_usage where appointment_id=aid and state='reserved') then raise exception 'Reservation missing'; end if;
 if public.get_public_barbershop(slug)::text like '%52998224725%' or public.get_public_barbershop(slug)::text like '%Test client%' then raise exception 'Public shop leaks customer identity'; end if;
 result:=public.save_barbershop_state(shop,test_payload,version);
 if not coalesce((result->>'conflict')::boolean,false) then raise exception 'Stale owner save was accepted'; end if;
 rejected:=false; begin perform public.create_plan_booking(slug,'52998224725','123456','','',1,'Profissional',d,'09:00'); exception when others then rejected:=true; end;
 if not rejected then raise exception 'Overdraft accepted'; end if;
 update public.barbershops set payload=jsonb_set(payload,'{appointments}',(select jsonb_agg(a||jsonb_build_object('status','Finalizado')) from jsonb_array_elements(payload->'appointments') a)),updated_at=clock_timestamp() where id=shop;
 update public.barbershops set payload=payload where id=shop;
 if (select count(*) from public.customer_plan_usage where membership_id=member and state='consumed')<>1 then raise exception 'Completion not idempotent'; end if;
 update public.barbershops set payload=jsonb_set(payload,'{appointments}',(select jsonb_agg(a||jsonb_build_object('status','Cancelado')) from jsonb_array_elements(payload->'appointments') a)),updated_at=clock_timestamp() where id=shop;
 if not exists(select 1 from public.customer_plan_usage where appointment_id=aid and state='released') then raise exception 'Cancellation did not release credit'; end if;
 result:=public.create_plan_booking(slug,'52998224725','123456','','',1,'Profissional',d,'09:00');
 rejected:=false; begin update public.barbershops set payload=jsonb_set(payload,'{appointments}',(select jsonb_agg(case when (a->>'id')::bigint=aid then a||jsonb_build_object('status','Confirmado') else a end) from jsonb_array_elements(payload->'appointments') a)) where id=shop; exception when others then rejected:=true; end;
 if not rejected then raise exception 'Reopening overdrawn reservation accepted'; end if;
 rejected:=false; begin perform public.create_plan_booking(slug,'52998224725','123456','','',2,'Profissional',current_date+31,'10:00'); exception when others then rejected:=true; end;
 if not rejected then raise exception 'Booking after expiry accepted'; end if;
 perform public.manage_customer_membership(member,'paused');
 if not public.lookup_customer_plan(slug,'52998224725','123456') ? 'error' then raise exception 'Paused membership available'; end if;
 perform public.manage_customer_membership(member,'active','654321');
 if not public.lookup_customer_plan(slug,'52998224725','123456') ? 'error' then raise exception 'Old PIN accepted after reset'; end if;
 if public.lookup_customer_plan(slug,'52998224725','654321') ? 'error' then raise exception 'New PIN unavailable'; end if;
 new_member:=public.activate_customer_plan(shop,template,'Test client','52998224725','27999990000',current_date,'654321');
 if not exists(select 1 from public.customer_memberships where id=member and status='canceled') or not exists(select 1 from public.customer_plan_usage where membership_id=member) then raise exception 'Renewal failed to preserve history'; end if;
 if (select count(*) from public.customer_plan_usage where membership_id=new_member)<>0 then raise exception 'Renewal did not reset balance'; end if;
 if has_table_privilege('anon','public.customer_memberships','select') or has_table_privilege('authenticated','public.customer_memberships','update') or has_schema_privilege('authenticated','barber_private','usage') then raise exception 'Sensitive table privileges exposed'; end if;
 if not has_function_privilege('anon','public.lookup_customer_plan(text,text,text)','execute') then raise exception 'Public lookup unavailable'; end if;
 execute 'set local role authenticated';
 if (select count(*) from public.customer_memberships where shop_id=shop)<>2 then raise exception 'Owner RLS denied'; end if;
 if (select count(*) from public.customer_plan_templates where shop_id=other_shop)<>0 then raise exception 'Cross-tenant RLS exposed'; end if;
 execute 'reset role';
end $$;
select 'PASS: tenant isolation, CPF/PIN, privacy, reservation, quota, completion, cancellation, conflict, expiry, pause, renewal, privileges' as test_result;
rollback;
